# Generated by Django 4.2 on 2024-12-27 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='movi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movi'),
        ),
        migrations.AddField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.ratingstar'),
        ),
        migrations.AddField(
            model_name='movishots',
            name='movi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movi'),
        ),
        migrations.AddField(
            model_name='movi',
            name='actor',
            field=models.ManyToManyField(related_name='film_actors', to='film.actor', verbose_name='актер'),
        ),
        migrations.AddField(
            model_name='movi',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='film.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='movi',
            name='director',
            field=models.ManyToManyField(related_name='film_directors', to='film.actor', verbose_name='режиссер'),
        ),
        migrations.AddField(
            model_name='movi',
            name='genres',
            field=models.ManyToManyField(to='film.genre', verbose_name='жанры'),
        ),
    ]
